name: "Flutter - Android"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.29.2
          architecture: x64

      - run flutter pub get

    -name: Build APK  
      - run: flutter build apk --release --build-name=1.0.0 --build-number=1






# push to master, main, develop
# pull request on main master
